theme: jekyll-theme-cayman
title: nift4
description: Creating things for/with Linux, Python, Minecraft and more.

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      title: nift4's Blog
      description: Writing about things that interest me or about my projects or something else.
